# This is a basic workflow to help you get started with Actions
name: LLAMA Workflowlib   

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #declaramos entorno para acceder a las variables y secretos del repositorio
    # y del entorno
    environment: DESARROLLO

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # llama otro worflowlib
      - name: Llamar workflowlib
        uses: ./.github/workflows/workflowlib_imprimevars.yml
        with:
          VAR_1: ${{ vars.VAR_SEGUNDO_APELLIDO_REPO }}
          VAR_2: ${{ vars.VAR_APELLIDO }}
          SECRETO_1: ${{ secrets.NOMBRE_SECRETO }}
          SECRETO_2: ${{ secrets.SEGUNDO_NOMBRE_ENTORNO }}
