# This is a basic workflow to help you get started with Actions
name: LLAMA Workflowlib   

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 preparar-vars:
    runs-on: ubuntu-latest
    environment: DESARROLLO
    outputs:
      var1: ${{ steps.set_vars.outputs.var1 }}
      var2: ${{ steps.set_vars.outputs.var2 }}
    steps:
      - name: Obtener variables
        id: set_vars
        run: |
          echo "var1=${{ vars.VAR_SEGUNDO_APELLIDO_REPO }}" >> $GITHUB_OUTPUT
          echo "var2=${{ vars.VAR_APELLIDO }}" >> $GITHUB_OUTPUT
          run: echo entorno DESARROLLO SECRET is ${{ secrets.SEGUNDO_NOMBRE_ENTORNO }}

 llamar-workflowlib:
    needs: preparar-vars
    uses: AL07183522/cursoGithub/.github/workflows/workflowlib_imprimevars.yml@main
    with:
      VAR_1: ${{ needs.preparar-vars.outputs.var1 }}
      VAR_2: ${{ needs.preparar-vars.outputs.var2 }}
    secrets:
      SECRETO_1: ${{ secrets.NOMBRE_SECRETO }}
      SECRETO_2: ${{ secrets.SEGUNDO_NOMBRE_ENTORNO }}
    
