name: Llama action desde otro repositorio

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  saludo_personalizado:
    runs-on: ubuntu-latest
    steps:
      - uses: AL07183522/githubaction_primeraction@main
        with:
          name: "Manuel de Jesus Ramiro Velazquez Tapia"