name: Llama action desde otro repositorio

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  saludo_personalizado:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout con token privado
        uses: actions/checkout@v4
       # with:
       #   token: ${{ secrets.ACTIONS_PAT }}
      - uses: AL07183522/githubaction_primeraction@main
        with:
          name: "Manuel de Jesus Ramiro Velazquez Tapia"